name: session7test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4-114.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  bottom_navy_bar: ^6.0.0
  video_player: ^2.7.2
  flutter_screenutil: ^5.9.0
  responsive_framework: ^1.1.1
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2

dev_dependencies:
  lint: ^2.2.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/Tech.png
    - images/login2.jpg
    - images/percentage.png
    - images/visualization.png
    - images/study.png
    - images/star.png
    - images/online.png
    - images/more.png
    - images/menu.png
    - videos/course1.mp4
    - assets/images/

